CATEGORY_CHOICES = [
    "Animal Husbandry",
    "Certificates",
    "Community Infrastructure and Services",
    "Crime and Safety",
    "Electricity and Power Supply",
    "Garbage and Unsanitary Practices",
    "Lakes",
    "Mobility - Roads, Footpaths and Infrastructure",
    "Mobility - Roads, Public transport",
    "Parks & Recreation",
    "Pollution",
    "Public Toilets",
    "Sewerage Systems",
    "Storm Water Drains",
    "Street lighting",
    "Streetlights",
    "Traffic and Road Safety",
    "Water Supply",
    "Water Supply and Services",
    "Yellow Spot",
]
CATEGORY_PROMPT_OPTIONS = " | ".join(CATEGORY_CHOICES) + " | other"

SUBCATEGORY_CHOICES = [
    "1B- Require New Public Toilet",
    "2A- Require New Footpath",
    "2B- Repair Broken Footpath",
    "2C- Remove Garbage or Debris on Footpath",
    "Air Pollution",
    "Build Dry Waste Collection Centre",
    "Certificates - Other",
    "Clearance Of Garbage Dump Or Black Spot",
    "Collection Of Door-to-door Garbage",
    "Construction Of Educational Institutions And Libraries",
    "Construction Of New Public Toilet",
    "Construction Of Roadside Drains",
    "Construction Of Sewage Lines",
    "Construction of flyovers/ underpass",
    "Construction of new footpaths",
    "Controlling Of Stray Cattle Or Maintenance Of Cattle Pound",
    "Desilting Existing Roadside Drains",
    "Desilting/Remove Blockage of Storm Water Drains",
    "Encroachment of cycle lane",
    "Eve Teasing/Public Nuisance",
    "Fixing/Reparing Potholes",
    "Flooding/Waterlogging Of Roads And Footpaths",
    "Fogging (Mosquito Menace) Or Pest Control",
    "Garbage Dumping In Vacant Lot/Land",
    "Installation Of New Streetlights",
    "Installation Of Traffic or Pedestrain Lights",
    "Installation/Maintenance Of Streetlight Timer",
    "Maintenance And Repair Of Manholes",
    "Maintenance And Repair Of Sewage Lines",
    "Maintenance And Repair Of Storm Water Drains",
    "Maintenance Of Lake Surrounding",
    "Maintenance Of Shopping And Commercial Complexes",
    "Maintenance Of existing Parks",
    "Maintenance/Repair Of Streetlights",
    "Management Of Hawkers and Vendors",
    "Need Covering Slabs For Roadside Drains",
    "Need Lane Markings/Street Name/Road Signages",
    "Noise Pollution",
    "One Way/No Entry",
    "Property Tax",
    "Reduce water leakage and wastage",
    "Regular Supply Of Electricity",
    "Regular Water Supply",
    "Removal Of Illegal Posters And Hoardings",
    "Removal Of Roadside Debris (Construction Material)",
    "Repair Of Existing Footpaths",
    "Report A Broken Footpath",
    "Report A Public Urination or Yellow Spot",
    "Report Garbage or Debris on Footpath",
    "Require A New Footpath",
    "Require A New Public Toilet",
    "Riding On Footpath",
    "Stop Water Leakage",
    "Stray Dog Sterilisation/Animal Birth Control (ABC)",
    "Tarring Or Asphalting Of Existing Road",
    "Tarring Or Asphalting Of Mud/Kutcha/Unpaved Road",
    "Traffic Jams/Congestion Or Bottlenecks",
    "Violating lane discipline",
]
SUBCATEGORY_PROMPT_OPTIONS = " | ".join(SUBCATEGORY_CHOICES) + " | other"

CIVIC_AGENCY_CHOICES = [
    "BBMP",
    "BCP",
    "BDA",
    "BESCOM",
    "BTP",
    "BWSSB",
    "KSPCB",
]
CIVIC_AGENCY_PROMPT_OPTIONS = " | ".join(CIVIC_AGENCY_CHOICES) + " | other"

CATEGORY_CIVIC_AGENCY_MAP = {
    "BBMP": ["Animal Husbandry", "Certificates", "Community Infrastructure and Services", "Garbage and Unsanitary Practices", "Lakes", 
             "Mobility - Roads, Footpaths and Infrastructure", "Parks & Recreation", "Public Toilets", "Storm Water Drains", 
             "Street lighting", "Streetlights", "Yellow Spot"],
    "BTP": ["Traffic and Road Safety"],
    "BESCOM": ["Electricity and Power Supply"],
    "BWSSB": ["Sewerage Systems", "Water Supply", "Water Supply and Services"],
    "KSPCB": ["Pollution"],
    "BDA": ["Mobility - Roads, Public transport"],
    "BCP": ["Crime and Safety"],
}